version: 2.1

orbs:
  hugo: circleci/hugo@0.4.1

jobs:
  deploy:
    docker:
      - image: cibuilds/base:latest
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "3e:c7:02:39:cf:c9:af:19:f2:52:d4:ad:b3:a0:cb:20"
      - deploy:
          name: Deploy to GitHub Pages
          command: sh ./.circleci/deploy.sh

workflows:
  version: 2
  pipeline:
    jobs:
      - hugo/build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - hugo/build

